language: go

go:
    - 1.4
before_install:
    - go get golang.org/x/tools/cmd/cover
    - go get golang.org/x/tools/cmd/vet
    - go get github.com/mattn/goveralls
script:
    - ./build.sh
after_success:
    - goveralls -coverprofile=profile.cov -service=travis-ci
sudo: false
